name: Build and test

on:
  push:
  pull_request:

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ ninja-build libcurl4-openssl-dev lld

      - name: Configure
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DMAIN=tests/arh2_light.cpp \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTING=ON

      - name: Build
        run: cmake --build build --parallel

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
